server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
    
  jpa:
    open-in-view: true
    hibernate:
      #create으로 하면 프로젝트 실행할때마다 재생성 하기 때문에 update로 바꾼다.
      ddl-auto: update
      naming:
       # 내가 지정한 필드명 그대로 사용한다.
       # SpringPhysicalNamingStrategy : 자동으로 내가 지정한 필드를 CamelToe에서 언더바 명명으로 바꿔준다 (emailName->email_name)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # JPA의 기본 넘버링 strategy를 따라가지 않고 연결된 DB의 넘버링을 선택한다 (False)        
      use-new-id-generator-mappings: false
    # console 창에 보여준다 true
    show-sql: true
    properties:
      # console 창에 query보여줄 때 이쁘게 보여준 true
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false